version: '3'
services:
  web:
    build:
      context: .
    image: bxtp4p/spring-petclinic:1.5.1
    ports:
      - "80:8080"
    networks:
      - spring-petclinic-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - "db"
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    image: bxtp4p/spring-petclinic-db:1.5.1
    networks:
      - spring-petclinic-net
networks:
  spring-petclinic-net: